upstream gunicorn_zahony {
    server 127.0.0.1:8009;
}

# HTTP (before SSL certificate is obtained)
server {
    listen 80;
    server_name zahony.hs-dev.cz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /static/ {
        alias /srv/apps/09_zahony/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://gunicorn_zahony;
    }
}
