# Generated by Django 6.0.5 on 2026-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_facing_diacritics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('asked', 'Poptáno'), ('ordered', 'Objednáno'), ('in_progress', 'Připravuje se'), ('awaiting_pickup', 'Čeká na vyzvednutí'), ('picked_up', 'Vyzvednuto'), ('cancelled', 'Zrušeno')], default='ordered', max_length=20, verbose_name='Stav'),
        ),
    ]
