# Generated by Django 6.0.5 on 2026-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_city_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vyzvednutí dne a čas'),
        ),
    ]
