# Generated by Django 6.0.5 on 2026-05-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_pickup_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Příjmení'),
        ),
    ]
