# Generated by Django 6.0.5 on 2026-05-12 12:51

from django.db import migrations, models
from django.utils import timezone


def copy_pickup_schedule(apps, schema_editor):
    Order = apps.get_model('home', 'Order')
    for order in Order.objects.exclude(pickup_at__isnull=True):
        pickup_local = timezone.localtime(order.pickup_at)
        order.pickup_date = pickup_local.date()
        order.pickup_time = pickup_local.time().replace(second=0, microsecond=0)
        if order.status == 'picked_up':
            order.picked_up_at = order.pickup_at
        order.save(update_fields=['pickup_date', 'pickup_time', 'picked_up_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pickup_date', 'pickup_time', 'customer__last_name'], 'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky'},
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Skutečně vyzvednuto'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum vyzvednutí'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Čas vyzvednutí'),
        ),
        migrations.RunPython(copy_pickup_schedule, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='order',
            name='pickup_at',
        ),
    ]
